### ISSUE TITLE
Some log lines have the wrong timestamp.

### ISSUE THREAD

**Issue by AdamAndersonMakeIT** [crazy-max/docker-pure-ftpd#5]
### Behaviour

Some log lines have timestamp according to TZ environment. Others have UTC timezone.

#### Steps to reproduce this issue

1. `docker run -ti --rm -p 21:2100 -e TZ=America/Edmonton crazymax/pure-ftpd:latest` also tried "Europe/Paris"
2. Initiate a connection: `ftp localhost`

#### Expected behaviour

All log lines should have Edmonton timestamp.

#### Actual behaviour

```
$ docker run -ti --rm -p 21:2100 -e TZ=America/Edmonton crazymax/pure-ftpd:latest
Use PureDB authentication method
Flags
  Secure: --maxclientsnumber 5 --maxclientsperip 5 --antiwarez --customerproof --dontresolve --norename --prohibitdotfilesread --prohibitdotfileswrite
  Additional:
  All: --bind 0.0.0.0,2100 --ipv4only --passiveportrange 30000:30009 --noanonymous --createhomedir --nochmod --syslogfacility ftp --forcepassiveip 205.234.47.168 --maxclientsnumber 5 --maxclientsperip 5 --antiwarez --customerproof --dontresolve --norename --prohibitdotfilesread --prohibitdotfileswrite --login puredb:/data/pureftpd.pdb
2020-04-23 13:16:24,770 INFO Included extra file "/etc/supervisord/pure-ftpd.conf" during parsing
2020-04-23 13:16:24,771 INFO Included extra file "/etc/supervisord/syslog-ng.conf" during parsing
2020-04-23 13:16:24,771 INFO Set uid to user 0 succeeded
2020-04-23 13:16:24,772 INFO supervisord started with pid 1
2020-04-23 13:16:25,785 INFO spawned: 'pure-ftpd' with pid 13
2020-04-23 13:16:25,793 INFO spawned: 'syslog-ng' with pid 14
2020-04-23 13:16:26,797 INFO success: pure-ftpd entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-04-23 13:16:26,797 INFO success: syslog-ng entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Apr 23 19:16:47 cb3e7eba6d53 pure-ftpd: (?@172.17.0.1) [INFO] New connection from 172.17.0.1
```
13:16 is Edmonton time (-06:00) but the connection log lines have 19:16 (UTC) (and also are a different format. I'm not worried about that).

### Configuration

* Docker version (type `docker --version`) : Docker version 18.09.2, build 6247962
* Docker compose version if applicable (type `docker-compose --version`) : docker-compose version 1.23.2, build 1110ad01
* Platform (Debian 9, Ubuntu 18.04, ...) : ubuntu 18.10
* System info (type `uname -a`) : Linux dsops 4.18.0-25-generic #26-Ubuntu SMP Mon Jun 24 09:32:08 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
* Include all necessary configuration files : `docker-compose.yml`, `.env`, ... ✔

### Docker info

```
Containers: 10
 Running: 0
 Paused: 0
 Stopped: 10
Images: 239
Server Version: 18.09.2
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9754871865f7fe2f4e74d43e2fc7ccd237edcbce
runc version: 09c8266bf2fcf9519a651b04ae54c967b9ab86ec
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.18.0-25-generic
Operating System: Ubuntu 18.10
OSType: linux
Architecture: x86_64
CPUs: 6
Total Memory: 7.767GiB
Name: dsops
ID: XKP4:MQJX:7T3C:V75Z:PXSI:GVO6:SRCZ:6YL4:HJPQ:DPOO:DK4A:WGLF
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine

WARNING: No swap limit support
```

### Container Logs:

Another example using Paris TZ:
```
docker run -ti --rm -p 21:2100 -e TZ=Europe/Paris crazymax/pure-ftpd:latest
Use PureDB authentication method
Flags
  Secure: --maxclientsnumber 5 --maxclientsperip 5 --antiwarez --customerproof --dontresolve --norename --prohibitdotfilesread --prohibitdotfileswrite
  Additional:
  All: --bind 0.0.0.0,2100 --ipv4only --passiveportrange 30000:30009 --noanonymous --createhomedir --nochmod --syslogfacility ftp --forcepassiveip 205.234.47.168 --maxclientsnumber 5 --maxclientsperip 5 --antiwarez --customerproof --dontresolve --norename --prohibitdotfilesread --prohibitdotfileswrite --login puredb:/data/pureftpd.pdb
2020-04-23 21:25:49,298 INFO Included extra file "/etc/supervisord/pure-ftpd.conf" during parsing
2020-04-23 21:25:49,298 INFO Included extra file "/etc/supervisord/syslog-ng.conf" during parsing
2020-04-23 21:25:49,298 INFO Set uid to user 0 succeeded
2020-04-23 21:25:49,301 INFO supervisord started with pid 1
2020-04-23 21:25:50,304 INFO spawned: 'pure-ftpd' with pid 14
2020-04-23 21:25:50,307 INFO spawned: 'syslog-ng' with pid 15
2020-04-23 21:25:51,309 INFO success: pure-ftpd entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-04-23 21:25:51,309 INFO success: syslog-ng entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Apr 23 19:26:02 f5be5c4b1865 pure-ftpd: (?@172.17.0.1) [INFO] New connection from 172.17.0.1
Apr 23 19:27:28 f5be5c4b1865 pure-ftpd: (?@172.17.0.1) [WARNING] Authentication failed for user [n]
Apr 23 19:27:29 f5be5c4b1865 pure-ftpd: (?@172.17.0.1) [INFO] Logout.
2020-04-23 21:27:30,817 INFO reaped unknown pid 18
```

**Comment by crazy-max** [comment]
@AdamAndersonMakeIT Should be fixed now, thanks for your input!

**Comment by AdamAndersonMakeIT** [comment]
Thank you!
But unfortunately, it is not fixed... the changes you made are there, but the issue remains:
```
$ docker run -ti --rm -p 21:2100 -e TZ=America/Edmonton crazymax/pure-ftpd:latest
Setting timezone to America/Edmonton...
Use PureDB authentication method
Flags
  Secure: --maxclientsnumber 5 --maxclientsperip 5 --antiwarez --customerproof --dontresolve --norename --prohibitdotfilesread --prohibitdotfileswrite
  Additional:
  All: --bind 0.0.0.0,2100 --ipv4only --passiveportrange 30000:30009 --noanonymous --createhomedir --nochmod --syslogfacility ftp --forcepassiveip 205.234.47.168 --maxclientsnumber 5 --maxclientsperip 5 --antiwarez --customerproof --dontresolve --norename --prohibitdotfilesread --prohibitdotfileswrite --login puredb:/data/pureftpd.pdb
2020-04-24 11:53:33,678 INFO Included extra file "/etc/supervisord/pure-ftpd.conf" during parsing
2020-04-24 11:53:33,678 INFO Included extra file "/etc/supervisord/syslog-ng.conf" during parsing
2020-04-24 11:53:33,678 INFO Set uid to user 0 succeeded
2020-04-24 11:53:33,680 INFO supervisord started with pid 1
2020-04-24 11:53:34,688 INFO spawned: 'pure-ftpd' with pid 14
2020-04-24 11:53:34,695 INFO spawned: 'syslog-ng' with pid 15
2020-04-24 11:53:35,698 INFO success: pure-ftpd entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-04-24 11:53:35,698 INFO success: syslog-ng entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Apr 24 17:53:44 7640146441e9 pure-ftpd: (?@172.17.0.1) [INFO] New connection from 172.17.0.1
Apr 24 17:53:56 7640146441e9 pure-ftpd: (?@172.17.0.1) [WARNING] Authentication failed for user [ah]
Apr 24 17:54:05 7640146441e9 pure-ftpd: (?@172.17.0.1) [INFO] Logout.
2020-04-24 11:54:05,191 INFO reaped unknown pid 18
```
Everything looks ok in the container...
```
$ docker exec -ti 76401 grep TZ /entrypoint.sh
TZ=${TZ:-UTC}
echo "Setting timezone to ${TZ}..."
ln -snf /usr/share/zoneinfo/${TZ} /etc/localtime
echo ${TZ} > /etc/timezone
```
```
$ docker exec -ti 76401 cat /etc/timezone
America/Edmonton
```
```
$ docker exec -ti 76401 ls -l /etc/localtime /usr/share/zoneinfo/America/Edmonton
lrwxrwxrwx    1 root     root            36 Apr 24 11:53 /etc/localtime -> /usr/share/zoneinfo/America/Edmonton
-rw-r--r--    2 root     root          2332 Sep 21  2019 /usr/share/zoneinfo/America/Edmonton
```

**Comment by crazy-max** [comment]
@AdamAndersonMakeIT Hum yeah we need to specify the timezone in syslog-ng too.

**Comment by AdamAndersonMakeIT** [comment]
Thank you, it is working now!
```
$ docker run -ti --rm -p 21:2100 -e TZ=America/Edmonton crazymax/pure-ftpd:latest
Setting timezone to America/Edmonton...
Use PureDB authentication method
Flags
  Secure: --maxclientsnumber 5 --maxclientsperip 5 --antiwarez --customerproof --dontresolve --norename --prohibitdotfilesread --prohibitdotfileswrite
  Additional:
  All: --bind 0.0.0.0,2100 --ipv4only --passiveportrange 30000:30009 --noanonymous --createhomedir --nochmod --syslogfacility ftp --forcepassiveip 205.234.47.168 --maxclientsnumber 5 --maxclientsperip 5 --antiwarez --customerproof --dontresolve --norename --prohibitdotfilesread --prohibitdotfileswrite --login puredb:/data/pureftpd.pdb
2020-04-24 13:03:24,067 INFO Included extra file "/etc/supervisord/pure-ftpd.conf" during parsing
2020-04-24 13:03:24,068 INFO Included extra file "/etc/supervisord/syslog-ng.conf" during parsing
2020-04-24 13:03:24,068 INFO Set uid to user 0 succeeded
2020-04-24 13:03:24,070 INFO supervisord started with pid 1
2020-04-24 13:03:25,078 INFO spawned: 'pure-ftpd' with pid 14
2020-04-24 13:03:25,080 INFO spawned: 'syslog-ng' with pid 15
2020-04-24 13:03:26,083 INFO success: pure-ftpd entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-04-24 13:03:26,084 INFO success: syslog-ng entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Apr 24 13:03:29 12dac2a66557 pure-ftpd: (?@172.17.0.1) [INFO] New connection from 172.17.0.1
Apr 24 13:03:43 12dac2a66557 pure-ftpd: (?@172.17.0.1) [WARNING] Authentication failed for user [test]
Apr 24 13:03:46 12dac2a66557 pure-ftpd: (?@172.17.0.1) [INFO] Logout.
2020-04-24 13:03:46,789 INFO reaped unknown pid 18
```
