### ISSUE TITLE
Container should stop if pure-ftpd cannot start

### ISSUE THREAD

**Issue by AdamAndersonMakeIT** [crazy-max/docker-pure-ftpd#6]
### Behaviour

Container runs idly if FTPD fails to start.

#### Steps to reproduce this issue

1. Run anything to listen on port 2100: `nc -l 2100` or crazymax/pure-ftpd.
2. `docker run -ti --rm --net host crazymax/pure-ftpd`

#### Expected behaviour

Container should exit when pure-ftpd cannot bind to port.

#### Actual behaviour

Container logs "Address in use" and pure-ftpd exits, but supervisord and syslog continue running, effectively useless: 

```
Setting timezone to UTC...
Use PureDB authentication method
Flags
  Secure: --maxclientsnumber 5 --maxclientsperip 5 --antiwarez --customerproof --dontresolve --norename --prohibitdotfilesread --prohibitdotfileswrite
  Additional:
  All: --bind 0.0.0.0,2100 --ipv4only --passiveportrange 30000:30009 --noanonymous --createhomedir --nochmod --syslogfacility ftp --forcepassiveip 205.234.47.168 --maxclientsnumber 5 --maxclientsperip 5 --antiwarez --customerproof --dontresolve --norename --prohibitdotfilesread --prohibitdotfileswrite --login puredb:/data/pureftpd.pdb
2020-05-14 18:10:18,110 INFO Included extra file "/etc/supervisord/pure-ftpd.conf" during parsing
2020-05-14 18:10:18,110 INFO Included extra file "/etc/supervisord/syslog-ng.conf" during parsing
2020-05-14 18:10:18,110 INFO Set uid to user 0 succeeded
2020-05-14 18:10:18,112 INFO supervisord started with pid 1
2020-05-14 18:10:19,121 INFO spawned: 'pure-ftpd' with pid 14
2020-05-14 18:10:19,127 INFO spawned: 'syslog-ng' with pid 15
Unable to start a standalone server: Address in use
2020-05-14 18:10:19,134 INFO exited: pure-ftpd (exit status 0; not expected)
2020-05-14 18:10:20,141 INFO spawned: 'pure-ftpd' with pid 16
2020-05-14 18:10:20,142 INFO success: syslog-ng entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Unable to start a standalone server: Address in use
2020-05-14 18:10:20,146 INFO exited: pure-ftpd (exit status 0; not expected)
May 14 18:10:20 dsops pure-ftpd: (?@?) [ERROR] Unable to start a standalone server: [Address in use]
2020-05-14 18:10:22,157 INFO spawned: 'pure-ftpd' with pid 18
Unable to start a standalone server: Address in use
2020-05-14 18:10:22,165 INFO exited: pure-ftpd (exit status 0; not expected)
May 14 18:10:22 dsops pure-ftpd: (?@?) [ERROR] Unable to start a standalone server: [Address in use]
2020-05-14 18:10:25,180 INFO spawned: 'pure-ftpd' with pid 19
Unable to start a standalone server: Address in use
2020-05-14 18:10:25,197 INFO exited: pure-ftpd (exit status 0; not expected)
May 14 18:10:25 dsops pure-ftpd: (?@?) [ERROR] Unable to start a standalone server: [Address in use]
2020-05-14 18:10:25,198 INFO gave up: pure-ftpd entered FATAL state, too many start retries too quickly
```
Container remains running but is not performing its function.

### Configuration

* Docker version:   18.09.2, build 6247962
* Platform: Ubuntu 18.04
* System info: Linux dsops 4.18.0-25-generic #26-Ubuntu SMP Mon Jun 24 09:32:08 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

### Docker info

```
Containers: 14
 Running: 1
 Paused: 0
 Stopped: 13
Images: 337
Server Version: 18.09.2
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9754871865f7fe2f4e74d43e2fc7ccd237edcbce
runc version: 09c8266bf2fcf9519a651b04ae54c967b9ab86ec
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.18.0-25-generic
Operating System: Ubuntu 18.10
OSType: linux
Architecture: x86_64
CPUs: 6
Total Memory: 7.767GiB
Name: dsops
ID: XKP4:MQJX:7T3C:V75Z:PXSI:GVO6:SRCZ:6YL4:HJPQ:DPOO:DK4A:WGLF
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine

WARNING: No swap limit support
```

**Comment by crazy-max** [comment]
Hi @AdamAndersonMakeIT,

I plan to replace supervisord with s6-overlay. That should fix this issue and enhanced this image. Anyway thanks for your input! Keep you in touch.

**Comment by crazy-max** [comment]
@AdamAndersonMakeIT Ok this image uses s6-overlay now. Can you reproduce your issue?

**Comment by AdamAndersonMakeIT** [comment]
The behaviour is different but I would say the bug is still there. S6 tries to start pure-ftp again when it fails to bind and exits. This appears to continue indefinitely until the container is killed. 

```
docker run -ti --rm --net host crazymax/pure-ftpd
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-config.sh: executing... 
Setting timezone to UTC...
Use PureDB authentication method
Flags
  Secure: --maxclientsnumber 5 --maxclientsperip 5 --antiwarez --customerproof --dontresolve --norename --prohibitdotfilesread --prohibitdotfileswrite
  Additional:
  All: --bind 0.0.0.0,2100 --ipv4only --passiveportrange 30000:30009 --noanonymous --createhomedir --nochmod --syslogfacility ftp --forcepassiveip 205.234.47.168 --maxclientsnumber 5 --maxclientsperip 5 --antiwarez --customerproof --dontresolve --norename --prohibitdotfilesread --prohibitdotfileswrite --login puredb:/data/pureftpd.pdb
[cont-init.d] 01-config.sh: exited 0.
[cont-init.d] 02-service.sh: executing... 
[cont-init.d] 02-service.sh: exited 0.
[cont-init.d] 03-uploadscript.sh: executing... 
ERROR: UPLOADSCRIPT program/script is not defined or does not exist
[cont-init.d] 03-uploadscript.sh: exited 1.
[cont-init.d] ~-socklog: executing... 
[cont-init.d] ~-socklog: exited 0.
[cont-init.d] done.
[services.d] starting services
Unable to start a standalone server: Address in use
[services.d] done.
ftp.err: May 21 20:36:04 pure-ftpd: (?@?) [ERROR] Unable to start a standalone server: [Address in use]
Unable to start a standalone server: Address in use
ftp.err: May 21 20:36:05 pure-ftpd: (?@?) [ERROR] Unable to start a standalone server: [Address in use]
.........
Unable to start a standalone server: Address in use
ftp.err: May 21 20:38:02 pure-ftpd: (?@?) [ERROR] Unable to start a standalone server: [Address in use]
^C[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
s6-svwait: fatal: timed out
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```

**Comment by AdamAndersonMakeIT** [comment]
Note that this behaviour only occurs when `--net host` is added to `docker run`.

Attempting to start the container without this option (using `-p 2100:2100` instead) will immediately fail because `docker-proxy` cannot bind the port; the container is created but never run. This is the desired outcome - container is not running; service is not available.

**Comment by crazy-max** [comment]
@AdamAndersonMakeIT Ok thanks for your input. I will use a finish script for the s6 service to handle this.

**Comment by crazy-max** [comment]
That should be fixed now.

**Comment by AdamAndersonMakeIT** [comment]
No, the behaviour is the same:
`nc -l 2100 & docker run -ti --rm --net host crazymax/pure-ftpd`
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-config.sh: executing... 
Setting timezone to UTC...
Use PureDB authentication method
Flags
  Secure: --maxclientsnumber 5 --maxclientsperip 5 --antiwarez --customerproof --dontresolve --norename --prohibitdotfilesread --prohibitdotfileswrite
  Additional:
  All: --bind 0.0.0.0,2100 --ipv4only --passiveportrange 30000:30009 --noanonymous --createhomedir --nochmod --syslogfacility ftp --forcepassiveip 205.234.47.168 --maxclientsnumber 5 --maxclientsperip 5 --antiwarez --customerproof --dontresolve --norename --prohibitdotfilesread --prohibitdotfileswrite --login puredb:/data/pureftpd.pdb
[cont-init.d] 01-config.sh: exited 0.
[cont-init.d] 02-service.sh: executing... 
[cont-init.d] 02-service.sh: exited 0.
[cont-init.d] 03-uploadscript.sh: executing... 
[cont-init.d] 03-uploadscript.sh: exited 0.
[cont-init.d] ~-socklog: executing... 
[cont-init.d] ~-socklog: exited 0.
[cont-init.d] done.
[services.d] starting services
Unable to start a standalone server: Address in use
ftp.err: May 22 03:12:33 pure-ftpd: (?@?) [ERROR] Unable to start a standalone server: [Address in use]
[services.d] done.
Unable to start a standalone server: Address in use
ftp.err: May 22 03:12:34 pure-ftpd: (?@?) [ERROR] Unable to start a standalone server: [Address in use]
Unable to start a standalone server: Address in use
ftp.err: May 22 03:12:35 pure-ftpd: (?@?) [ERROR] Unable to start a standalone server: [Address in use]
Unable to start a standalone server: Address in use
ftp.err: May 22 03:12:36 pure-ftpd: (?@?) [ERROR] Unable to start a standalone server: [Address in use]
Unable to start a standalone server: Address in use
ftp.err: May 22 03:12:37 pure-ftpd: (?@?) [ERROR] Unable to start a standalone server: [Address in use]
Unable to start a standalone server: Address in use
ftp.err: May 22 03:12:38 pure-ftpd: (?@?) [ERROR] Unable to start a standalone server: [Address in use]
Unable to start a standalone server: Address in use
ftp.err: May 22 03:12:39 pure-ftpd: (?@?) [ERROR] Unable to start a standalone server: [Address in use]
Unable to start a standalone server: Address in use
ftp.err: May 22 03:12:40 pure-ftpd: (?@?) [ERROR] Unable to start a standalone server: [Address in use]
Unable to start a standalone server: Address in use
ftp.err: May 22 03:12:41 pure-ftpd: (?@?) [ERROR] Unable to start a standalone server: [Address in use]
Unable to start a standalone server: Address in use
ftp.err: May 22 03:12:42 pure-ftpd: (?@?) [ERROR] Unable to start a standalone server: [Address in use]
Unable to start a standalone server: Address in use
ftp.err: May 22 03:12:43 pure-ftpd: (?@?) [ERROR] Unable to start a standalone server: [Address in use]
Unable to start a standalone server: Address in use
ftp.err: May 22 03:12:44 pure-ftpd: (?@?) [ERROR] Unable to start a standalone server: [Address in use]
Unable to start a standalone server: Address in use
ftp.err: May 22 03:12:45 pure-ftpd: (?@?) [ERROR] Unable to start a standalone server: [Address in use]
Unable to start a standalone server: Address in use
ftp.err: May 22 03:12:46 pure-ftpd: (?@?) [ERROR] Unable to start a standalone server: [Address in use]
Unable to start a standalone server: Address in use
ftp.err: May 22 03:12:47 pure-ftpd: (?@?) [ERROR] Unable to start a standalone server: [Address in use]
Unable to start a standalone server: Address in use
ftp.err: May 22 03:12:48 pure-ftpd: (?@?) [ERROR] Unable to start a standalone server: [Address in use]
Unable to start a standalone server: Address in use
ftp.err: May 22 03:12:49 pure-ftpd: (?@?) [ERROR] Unable to start a standalone server: [Address in use]
Unable to start a standalone server: Address in use
ftp.err: May 22 03:12:50 pure-ftpd: (?@?) [ERROR] Unable to start a standalone server: [Address in use]
Unable to start a standalone server: Address in use
ftp.err: May 22 03:12:51 pure-ftpd: (?@?) [ERROR] Unable to start a standalone server: [Address in use]
Unable to start a standalone server: Address in use
ftp.err: May 22 03:12:52 pure-ftpd: (?@?) [ERROR] Unable to start a standalone server: [Address in use]
Unable to start a standalone server: Address in use
ftp.err: May 22 03:12:53 pure-ftpd: (?@?) [ERROR] Unable to start a standalone server: [Address in use]
Unable to start a standalone server: Address in use
ftp.err: May 22 03:12:54 pure-ftpd: (?@?) [ERROR] Unable to start a standalone server: [Address in use]
Unable to start a standalone server: Address in use
ftp.err: May 22 03:12:55 pure-ftpd: (?@?) [ERROR] Unable to start a standalone server: [Address in use]
Unable to start a standalone server: Address in use
ftp.err: May 22 03:12:56 pure-ftpd: (?@?) [ERROR] Unable to start a standalone server: [Address in use]
Unable to start a standalone server: Address in use
ftp.err: May 22 03:12:57 pure-ftpd: (?@?) [ERROR] Unable to start a standalone server: [Address in use]
Unable to start a standalone server: Address in use
ftp.err: May 22 03:12:58 pure-ftpd: (?@?) [ERROR] Unable to start a standalone server: [Address in use]
Unable to start a standalone server: Address in use
ftp.err: May 22 03:12:59 pure-ftpd: (?@?) [ERROR] Unable to start a standalone server: [Address in use]
Unable to start a standalone server: Address in use
ftp.err: May 22 03:13:00 pure-ftpd: (?@?) [ERROR] Unable to start a standalone server: [Address in use]
Unable to start a standalone server: Address in use
ftp.err: May 22 03:13:02 pure-ftpd: (?@?) [ERROR] Unable to start a standalone server: [Address in use]
Unable to start a standalone server: Address in use
ftp.err: May 22 03:13:03 pure-ftpd: (?@?) [ERROR] Unable to start a standalone server: [Address in use]
Unable to start a standalone server: Address in use
ftp.err: May 22 03:13:04 pure-ftpd: (?@?) [ERROR] Unable to start a standalone server: [Address in use]
Unable to start a standalone server: Address in use
ftp.err: May 22 03:13:05 pure-ftpd: (?@?) [ERROR] Unable to start a standalone server: [Address in use]
Unable to start a standalone server: Address in use
ftp.err: May 22 03:13:06 pure-ftpd: (?@?) [ERROR] Unable to start a standalone server: [Address in use]
Unable to start a standalone server: Address in use
ftp.err: May 22 03:13:07 pure-ftpd: (?@?) [ERROR] Unable to start a standalone server: [Address in use]
Unable to start a standalone server: Address in use
ftp.err: May 22 03:13:08 pure-ftpd: (?@?) [ERROR] Unable to start a standalone server: [Address in use]
Unable to start a standalone server: Address in use
ftp.err: May 22 03:13:09 pure-ftpd: (?@?) [ERROR] Unable to start a standalone server: [Address in use]
Unable to start a standalone server: Address in use
ftp.err: May 22 03:13:10 pure-ftpd: (?@?) [ERROR] Unable to start a standalone server: [Address in use]
Unable to start a standalone server: Address in use
ftp.err: May 22 03:13:11 pure-ftpd: (?@?) [ERROR] Unable to start a standalone server: [Address in use]
Unable to start a standalone server: Address in use
ftp.err: May 22 03:13:12 pure-ftpd: (?@?) [ERROR] Unable to start a standalone server: [Address in use]
Unable to start a standalone server: Address in use
ftp.err: May 22 03:13:13 pure-ftpd: (?@?) [ERROR] Unable to start a standalone server: [Address in use]
Unable to start a standalone server: Address in use
ftp.err: May 22 03:13:14 pure-ftpd: (?@?) [ERROR] Unable to start a standalone server: [Address in use]
Unable to start a standalone server: Address in use
ftp.err: May 22 03:13:15 pure-ftpd: (?@?) [ERROR] Unable to start a standalone server: [Address in use]
Unable to start a standalone server: Address in use
ftp.err: May 22 03:13:16 pure-ftpd: (?@?) [ERROR] Unable to start a standalone server: [Address in use]
Unable to start a standalone server: Address in use
ftp.err: May 22 03:13:17 pure-ftpd: (?@?) [ERROR] Unable to start a standalone server: [Address in use]
Unable to start a standalone server: Address in use
ftp.err: May 22 03:13:18 pure-ftpd: (?@?) [ERROR] Unable to start a standalone server: [Address in use]
Unable to start a standalone server: Address in use
ftp.err: May 22 03:13:19 pure-ftpd: (?@?) [ERROR] Unable to start a standalone server: [Address in use]
Unable to start a standalone server: Address in use
ftp.err: May 22 03:13:20 pure-ftpd: (?@?) [ERROR] Unable to start a standalone server: [Address in use]
Unable to start a standalone server: Address in use
ftp.err: May 22 03:13:21 pure-ftpd: (?@?) [ERROR] Unable to start a standalone server: [Address in use]
Unable to start a standalone server: Address in use
ftp.err: May 22 03:13:22 pure-ftpd: (?@?) [ERROR] Unable to start a standalone server: [Address in use]
Unable to start a standalone server: Address in use
ftp.err: May 22 03:13:23 pure-ftpd: (?@?) [ERROR] Unable to start a standalone server: [Address in use]
Unable to start a standalone server: Address in use
ftp.err: May 22 03:13:24 pure-ftpd: (?@?) [ERROR] Unable to start a standalone server: [Address in use]
^C[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
s6-svwait: fatal: timed out
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```

**Comment by crazy-max** [comment]
@AdamAndersonMakeIT I put back the finish script I took out. Can you try again?

**Comment by AdamAndersonMakeIT** [comment]
There is a parse error but it still keeps restarting.

`nc -l 2100`
`docker run -ti --rm --net host crazymax/pure-ftpd`
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-config.sh: executing... 
Setting timezone to UTC...
Use PureDB authentication method
Flags
  Secure: --maxclientsnumber 5 --maxclientsperip 5 --antiwarez --customerproof --dontresolve --norename --prohibitdotfilesread --prohibitdotfileswrite
  Additional:
  All: --bind 0.0.0.0,2100 --ipv4only --passiveportrange 30000:30009 --noanonymous --createhomedir --nochmod --syslogfacility ftp --forcepassiveip 205.234.47.168 --maxclientsnumber 5 --maxclientsperip 5 --antiwarez --customerproof --dontresolve --norename --prohibitdotfilesread --prohibitdotfileswrite --login puredb:/data/pureftpd.pdb
[cont-init.d] 01-config.sh: exited 0.
[cont-init.d] 02-service.sh: executing... 
[cont-init.d] 02-service.sh: exited 0.
[cont-init.d] 03-uploadscript.sh: executing... 
[cont-init.d] 03-uploadscript.sh: exited 0.
[cont-init.d] ~-socklog: executing... 
[cont-init.d] ~-socklog: exited 0.
[cont-init.d] done.
[services.d] starting services
Unable to start a standalone server: Address in use
[services.d] done.
s6-test: fatal: parse error at argument 0
ftp.err: May 22 04:42:01 pure-ftpd: (?@?) [ERROR] Unable to start a standalone server: [Address in use]
Unable to start a standalone server: Address in use
ftp.err: May 22 04:42:02 pure-ftpd: (?@?) [ERROR] Unable to start a standalone server: [Address in use]
s6-test: fatal: parse error at argument 0
Unable to start a standalone server: Address in use
ftp.err: May 22 04:42:03 pure-ftpd: (?@?) [ERROR] Unable to start a standalone server: [Address in use]
s6-test: fatal: parse error at argument 0
Unable to start a standalone server: Address in use
ftp.err: May 22 04:42:04 pure-ftpd: (?@?) [ERROR] Unable to start a standalone server: [Address in use]
s6-test: fatal: parse error at argument 0
Unable to start a standalone server: Address in use
ftp.err: May 22 04:42:05 pure-ftpd: (?@?) [ERROR] Unable to start a standalone server: [Address in use]
s6-test: fatal: parse error at argument 0
Unable to start a standalone server: Address in use
ftp.err: May 22 04:42:06 pure-ftpd: (?@?) [ERROR] Unable to start a standalone server: [Address in use]
s6-test: fatal: parse error at argument 0
Unable to start a standalone server: Address in use
ftp.err: May 22 04:42:07 pure-ftpd: (?@?) [ERROR] Unable to start a standalone server: [Address in use]
s6-test: fatal: parse error at argument 0
Unable to start a standalone server: Address in use
ftp.err: May 22 04:42:08 pure-ftpd: (?@?) [ERROR] Unable to start a standalone server: [Address in use]
s6-test: fatal: parse error at argument 0
Unable to start a standalone server: Address in use
ftp.err: May 22 04:42:09 pure-ftpd: (?@?) [ERROR] Unable to start a standalone server: [Address in use]
s6-test: fatal: parse error at argument 0
^C[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
s6-svwait: fatal: timed out
[s6-finish] sending all processes the TERM signal.
s6-log: warning: unable to read from stdin: Bad file descriptor
[s6-finish] sending all processes the KILL signal and exiting.
```

**Comment by crazy-max** [comment]
@AdamAndersonMakeIT Ok I was able to reproduce with `nc -lp 2100`. I have made new changes, can you try?

```
[cont-init.d] 01-config.sh: exited 0.
[cont-init.d] 02-service.sh: executing...
[cont-init.d] 02-service.sh: exited 0.
[cont-init.d] 03-uploadscript.sh: executing...
[cont-init.d] 03-uploadscript.sh: exited 0.
[cont-init.d] ~-socklog: executing...
[cont-init.d] ~-socklog: exited 0.
[cont-init.d] done.
[services.d] starting services
Unable to start a standalone server: Address in use
[services.d] done.
ftp.err: May 22 06:44:30 pure-ftpd: (?@?) [ERROR] Unable to start a standalone server: [Address in use]
[app/finish] finishing (/var/run/s6/etc/cont-init.d/02-service.sh  0)
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
s6-svwait: fatal: timed out
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```
